#log4j2 config file.
logging:
  config: classpath:log4j2-dev.xml
  
spring:
  sleuth:
    sampler:
      percentage: 0.1 # percentage 表示采样的百分比，1.0表示百分百采样，生产建议设置为0.1
    rxjava:
      schedulers:
        hook:
          enabled: false
  rabbitmq:
    host: 10.10.3.67
    port: 13001
    username: root
    password: rootpass123    